// ═══════════════════════════════════════════════════════════
// IMPORT RÉSERVATIONS ABRACADAPARC 2026
// Coller dans la console du navigateur sur abracadaparc.github.io/-rh
// ═══════════════════════════════════════════════════════════

(function() {
  const data = {
  "19d4387e6e5dlrm": {
    "id": "19d4387e6e5dlrm",
    "segment": "anniversaire",
    "statut": "4",
    "ref": "#14879",
    "nom_contact": "Marlene Frezza",
    "tel": "0659216449",
    "email_contact": "mbintein@yahoo.com",
    "date": "2026-04-11",
    "heure_debut": "14:00",
    "heure_fin": "17:00",
    "formule_id": "fantastique",
    "prenom_enfant": "Lisa-Marie",
    "age_enfant": "9",
    "effectif_enfants": "8",
    "gateau_nacima": true,
    "gateau_type": "Tarte aux pommes",
    "gateau_inscription": "",
    "gateau_allergies": "",
    "gateau_commande": false,
    "option_animateur": false,
    "montant_total": "208",
    "acompte_paye": "208",
    "mode_paiement": "Cartes",
    "notes": "⚠️ DOUBLON 11/04 même créneau que #14911 Adèle Descout — vérifier espaces séparés. Liste invités: Paul Louca Alix Vanessa Alya Charles Helena",
    "walkin": false,
    "created_at": "2026-03-31T10:00:00.000Z",
    "updated_at": "2026-03-31T10:00:00.000Z"
  },
  "19d4387e6e6pwc1": {
    "id": "19d4387e6e6pwc1",
    "segment": "anniversaire",
    "statut": "4",
    "ref": "#14890",
    "nom_contact": "Laura Charrier",
    "tel": "0761770312",
    "email_contact": "lauracharrier12@gmail.com",
    "date": "2026-04-05",
    "heure_debut": "14:00",
    "heure_fin": "17:00",
    "formule_id": "fantastique",
    "prenom_enfant": "Owen",
    "age_enfant": "3",
    "effectif_enfants": "9",
    "gateau_nacima": false,
    "gateau_type": "Votre gâteau — famille apporte",
    "gateau_inscription": "",
    "gateau_allergies": "",
    "gateau_commande": false,
    "option_animateur": true,
    "montant_total": "334",
    "acompte_paye": "100",
    "mode_paiement": "Cartes",
    "notes": "🚨 J-5 DEMAIN — Gâteau famille (droit gâteau +10€). Animateur inclus (+100€). Appeler Laura pour confirmer gâteau: 07 61 77 03 12",
    "walkin": false,
    "created_at": "2026-03-31T10:00:00.000Z",
    "updated_at": "2026-03-31T10:00:00.000Z"
  },
  "19d4387e6e6wkkb": {
    "id": "19d4387e6e6wkkb",
    "segment": "anniversaire",
    "statut": "4",
    "ref": "#14911",
    "nom_contact": "Nathalie Descout",
    "tel": "0671730286",
    "email_contact": "nathalie.descout@nadvise.com",
    "date": "2026-04-11",
    "heure_debut": "14:00",
    "heure_fin": "17:00",
    "formule_id": "fantastique",
    "prenom_enfant": "Adèle",
    "age_enfant": "9",
    "effectif_enfants": "9",
    "gateau_nacima": false,
    "gateau_type": "Votre gâteau — famille apporte",
    "gateau_inscription": "",
    "gateau_allergies": "",
    "gateau_commande": false,
    "option_animateur": false,
    "montant_total": "234",
    "acompte_paye": "100",
    "mode_paiement": "Cartes",
    "notes": "⚠️ DOUBLON 11/04 même créneau que #14879 Lisa-Marie Frezza — vérifier espaces séparés. Liste: Louise Luna Inès Suzanne Marie Léopoldine Philomène Victoria — 2 adultes Nathalie & Octave",
    "walkin": false,
    "created_at": "2026-03-31T10:00:00.000Z",
    "updated_at": "2026-03-31T10:00:00.000Z"
  },
  "19d4387e6e6nlf6": {
    "id": "19d4387e6e6nlf6",
    "segment": "anniversaire",
    "statut": "4",
    "ref": "#14937",
    "nom_contact": "Jennifer Zwick",
    "tel": "+33640369700",
    "email_contact": "jennylr83@gmail.com",
    "date": "2026-05-02",
    "heure_debut": "10:00",
    "heure_fin": "13:00",
    "formule_id": "fantastique",
    "prenom_enfant": "Anna",
    "age_enfant": "10",
    "effectif_enfants": "8",
    "gateau_nacima": true,
    "gateau_type": "Moelleux chocolat",
    "gateau_inscription": "",
    "gateau_allergies": "",
    "gateau_commande": false,
    "option_animateur": false,
    "montant_total": "176",
    "acompte_paye": "100",
    "mode_paiement": "Cartes",
    "notes": "Liste invités: Anna Loelia Lise Loïs Eden Manon Margaux Morganne",
    "walkin": false,
    "created_at": "2026-03-31T10:00:00.000Z",
    "updated_at": "2026-03-31T10:00:00.000Z"
  },
  "19d4387e6e6baty": {
    "id": "19d4387e6e6baty",
    "segment": "anniversaire",
    "statut": "4",
    "ref": "#14948",
    "nom_contact": "Céline Delavaquerie",
    "tel": "0667809423",
    "email_contact": "cline191287@hotmail.com",
    "date": "2026-05-30",
    "heure_debut": "14:00",
    "heure_fin": "17:00",
    "formule_id": "fantastique",
    "prenom_enfant": "Florian",
    "age_enfant": "10",
    "effectif_enfants": "8",
    "gateau_nacima": true,
    "gateau_type": "Moelleux chocolat",
    "gateau_inscription": "",
    "gateau_allergies": "",
    "gateau_commande": false,
    "option_animateur": false,
    "montant_total": "208",
    "acompte_paye": "100",
    "mode_paiement": "Cartes",
    "notes": "",
    "walkin": false,
    "created_at": "2026-03-31T10:00:00.000Z",
    "updated_at": "2026-03-31T10:00:00.000Z"
  },
  "19d4387e6e6ttgb": {
    "id": "19d4387e6e6ttgb",
    "segment": "anniversaire",
    "statut": "4",
    "ref": "#14959",
    "nom_contact": "Elodie Betoule",
    "tel": "0745160582",
    "email_contact": "elodie95190@gmail.com",
    "date": "2026-04-04",
    "heure_debut": "14:00",
    "heure_fin": "17:00",
    "formule_id": "fantastique",
    "prenom_enfant": "Leny & Tom",
    "age_enfant": "7",
    "effectif_enfants": "15",
    "gateau_nacima": true,
    "gateau_type": "Moelleux chocolat × 2 (1 inclus + 1 commandé)",
    "gateau_inscription": "",
    "gateau_allergies": "",
    "gateau_commande": false,
    "option_animateur": false,
    "montant_total": "390",
    "acompte_paye": "100",
    "mode_paiement": "Cartes",
    "notes": "🚨🚨 J-4 SAMEDI — 2 anniversaires: Leny 7 ans + Tom 4 ans. 2 gâteaux moelleux choco à commander Nacima 06 19 30 06 39. 15 enfants. Solde 290€",
    "walkin": false,
    "created_at": "2026-03-31T10:00:00.000Z",
    "updated_at": "2026-03-31T10:00:00.000Z"
  },
  "19d4387e6e6kg78": {
    "id": "19d4387e6e6kg78",
    "segment": "anniversaire",
    "statut": "4",
    "ref": "#14978",
    "nom_contact": "Laura Famularo",
    "tel": "0619299867",
    "email_contact": "famularo.laura@gmail.com",
    "date": "2026-05-30",
    "heure_debut": "10:00",
    "heure_fin": "13:00",
    "formule_id": "gourmand",
    "prenom_enfant": "Louis & Romy",
    "age_enfant": "5",
    "effectif_enfants": "10",
    "gateau_nacima": true,
    "gateau_type": "Moelleux chocolat",
    "gateau_inscription": "",
    "gateau_allergies": "",
    "gateau_commande": false,
    "option_animateur": false,
    "montant_total": "290",
    "acompte_paye": "100",
    "mode_paiement": "Cartes",
    "notes": "⚠️ MÊME JOUR que #14948 Florian Delavaquerie — 2 créneaux différents (10h-13h et 14h-17h) ✅",
    "walkin": false,
    "created_at": "2026-03-31T10:00:00.000Z",
    "updated_at": "2026-03-31T10:00:00.000Z"
  },
  "19d4387e6e6dwsk": {
    "id": "19d4387e6e6dwsk",
    "segment": "anniversaire",
    "statut": "4",
    "ref": "#14992",
    "nom_contact": "Guillaume Garcia",
    "tel": "0698914752",
    "email_contact": "garcia92guillaume@gmail.com",
    "date": "2026-05-03",
    "heure_debut": "10:00",
    "heure_fin": "13:00",
    "formule_id": "fantastique",
    "prenom_enfant": "Clémence",
    "age_enfant": "6",
    "effectif_enfants": "9",
    "gateau_nacima": true,
    "gateau_type": "Moelleux chocolat",
    "gateau_inscription": "",
    "gateau_allergies": "",
    "gateau_commande": false,
    "option_animateur": false,
    "montant_total": "198",
    "acompte_paye": "100",
    "mode_paiement": "Cartes",
    "notes": "",
    "walkin": false,
    "created_at": "2026-03-31T10:00:00.000Z",
    "updated_at": "2026-03-31T10:00:00.000Z"
  },
  "19d4387e6e63mkg": {
    "id": "19d4387e6e63mkg",
    "segment": "anniversaire",
    "statut": "4",
    "ref": "#15005",
    "nom_contact": "KAINA Medroub-Dahan",
    "tel": "0782737929",
    "email_contact": "kaina.medroub@gmail.com",
    "date": "2026-05-24",
    "heure_debut": "10:00",
    "heure_fin": "13:00",
    "formule_id": "gourmand",
    "prenom_enfant": "Romy & Charly",
    "age_enfant": "3",
    "effectif_enfants": "8",
    "gateau_nacima": true,
    "gateau_type": "Moelleux chocolat",
    "gateau_inscription": "",
    "gateau_allergies": "",
    "gateau_commande": false,
    "option_animateur": false,
    "montant_total": "232",
    "acompte_paye": "100",
    "mode_paiement": "Cartes",
    "notes": "3 adultes supplémentaires (+30€ déjà payés). Liste invités: Ava Sasha Marlon Liam",
    "walkin": false,
    "created_at": "2026-03-31T10:00:00.000Z",
    "updated_at": "2026-03-31T10:00:00.000Z"
  }
};

  // 1. Sauvegarde Firebase
  try {
    const db = firebase.database();
    db.ref('abracadaparc/reservations').set(JSON.stringify(data))
      .then(() => console.log('✅ Firebase mis à jour — ' + Object.keys(data).length + ' réservations'))
      .catch(e => console.error('❌ Firebase:', e));
  } catch(e) { console.warn('Firebase indisponible:', e); }

  // 2. Sauvegarde localStorage (fallback)
  try {
    localStorage.setItem('abr_reservations', JSON.stringify(data));
    console.log('✅ localStorage mis à jour');
  } catch(e) { console.warn('localStorage:', e); }

  // 3. Mise à jour affichage si ReservationsTab est chargé
  try {
    if (window.ReservationsTab) {
      window.ReservationsTab.state.reservations = data;
      window.ReservationsTab.render();
      console.log('✅ Interface mise à jour');
    }
  } catch(e) { console.warn('Render:', e); }

  alert('✅ ' + Object.keys(data).length + ' réservations importées !\n\n🚨 URGENT :\n• Nacima pour Betoule (SAM 4 avril) : 06 19 30 06 39\n• Vérifier doublon 11 avril (Lisa-Marie + Adèle)\n• Appeler Laura Charrier pour Owen (DIM 5 avril)');
})();
